package com.nandini.knowledgeassistant.common.audit;

public enum AuditAction {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_DELETED,
    DOCUMENT_REPROCESS_REQUESTED,
    DOCUMENT_ACCESS_GRANTED,
    DOCUMENT_ACCESS_REVOKED,
    DOCUMENT_PROCESSED,
    DOCUMENT_PROCESSING_FAILED,
    QUESTION_ANSWERED,
    QUESTION_REJECTED
}
